name: X9/A5 Camera Handler
version: 0.0.31
slug: camera_handler
description: A custom Node.js server handling X9/A5 Cameras inside Home Assistant.
url: https://github.com/YeonV/home-assistant-addons/tree/master/camera-handler
arch:
  - armv7
  - aarch64
  - amd64
stage: stable
init: false
ingress: true
homeassistant_api: true
hassio_api: true
hassio_role: manager
host_network: true
ingress_stream: true
services:
  - mqtt:want
ingress_port: 5000
ingress_timeout: 60
ingress_entry: "/"
panel_icon: mdi:cctv
panel_title: Camera Handler
startup: application
boot: manual
options: {}
schema: {}
image: ghcr.io/yeonv/{arch}-camera-handler

{"name":"CamReverse TBAT610268VZJFB","unique_id":"cam_reverse_TBAT610268VZJFB","topic":"homeassistant/camera/cam_reverse_TBAT610268VZJFB/state","mjpeg_url":"http://192.168.1.47:5000/camera/TBAT610268VZJFB","still_image_url":"http://192.168.1.47:5000/camera/TBAT610268VZJFB","device":{"identifiers":["cam_reverse_TBAT610268VZJFB"],"name":"CamReverse Camera TBAT610268VZJFB","manufacturer":"cam-reverse-addon","model":"Reversed Stream","sw_version":"0.0.1"}}
