name: Camera Handler
version: 0.0.2
slug: camera_handler
description: A custom Node.js server for Home Assistant.
url: https://github.com/YeonV/home-assistant-addons/tree/master/camera-handler
arch:
  - armv7
  - aarch64
  - amd64
stage: stable
ingress: true
homeassistant_api: true
hassio_api: true
hassio_role: default
host_network: true
ingress_stream: true
# services:
#   - mqtt:want
ingress_port: 5000
ingress_timeout: 60
ingress_entry: "/"
panel_icon: mdi:cctv
panel_title: Camera Handler
startup: application
boot: manual
options: {}
schema: {}
image: ghcr.io/yeonv/{arch}-camera-handler