---
name: ledfx-frontend_YZ
version: beta
slug: ledfx-beta
description: A network based LED effect controller with support for advanced real-time audio effects!
url: https://github.com/YeonV/ledfx-home-assistant-addon/tree/master/ledfx-beta
#webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
audio: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
auth_api: true
ingress: true
ingress_stream: true
ingress_port: 8888
panel_icon: mdi:emoticon-devil-outline
panel_title: LedFx
map:
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  leave_front_door_open: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  leave_front_door_open: bool?
