---
name: LedFx (beta)
version: beta5
slug: ledfx-beta
description: A network based LED effect controller with support for advanced real-time audio effects!
url: https://github.com/YeonV/home-assistant-addons/tree/master/ledfx-beta
audio: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
auth_api: true
ingress: true
ingress_stream: true
panel_icon: mdi:emoticon-devil-outline
panel_title: LedFx
map:
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  leave_front_door_open: bool?
image: "ghcr.io/yeonv/{arch}-addon-ledfx"