---
name: LedFx Addon
<<<<<<< HEAD
version: 2.0.76
=======
version: 2.0.75
>>>>>>> a5e92e3a8980867bb686084f08abe0e4cadb18f3
slug: ledfx-beta
description: A network based LED effect controller with support for advanced real-time audio effects!
url: https://github.com/YeonV/home-assistant-addons/tree/master/ledfx-beta
audio: true
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
auth_api: true
ingress: true
ingress_stream: true
ingress_port: 8989
ingress_entry: "#/./"
panel_icon: mdi:emoticon-devil-outline
panel_title: LedFx
init: false
map:
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  leave_front_door_open: bool?
image: "ghcr.io/yeonv/{arch}-addon-ledfx"
