name: Camera Handler
version: 1.1.14
slug: nodejs_server
description: A custom Node.js server for Home Assistant.
url: https://github.com/YeonV/home-assistant-addons/tree/master/nodejs-server
arch:
  - armv7
  - aarch64
  - amd64
ingress: true
hassio_api: true
hassio_role: default
host_network: true
ingress_stream: true
ingress_port: 0
ingress_entry: "/"
startup: application
boot: auto
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface
options: {}
schema: {}
image: ghcr.io/yeonv/{arch}-nodejs-server