name: Camera Handler
version: 1.1.37
slug: nodejs_server
description: A custom Node.js server for Home Assistant.
url: https://github.com/YeonV/home-assistant-addons/tree/master/nodejs-server
arch:
  - armv7
  - aarch64
  - amd64
stage: experimental
ingress: true
homeassistant_api: true
hassio_api: true
hassio_role: default
host_network: true
ingress_stream: true
ingress_port: 5000
ingress_timeout: 60
ingress_entry: "/"
panel_icon: mdi:cctv
panel_title: Camera Handler
startup: application
boot: auto
options: {}
schema: {}
image: ghcr.io/yeonv/{arch}-nodejs-server